### ISSUE TITLE
Implement new "define" instruction

### ISSUE THREAD

**Issue by andrey-zakharov** [stationeering/stationeers-ic#6]
from 0.2.1820.8428

"Added a define command to the IC that allows programmers to create constant values without using a register."

**Comment by melair** [comment]
Need to identify how to parse this successfully, probably can be engineered into _getRegister in the path for strings/integer that aren't remapped to aliases.

```
"define":{"description":"creates a label that will be replaced throughout the program with the provided value","example":"<color=yellow>define</color> <color=white>str</color> <color=white>num</color>"}
```

**Comment by melair** [comment]
Actually, I did this a few months ago, and forgot to close the ticket. :D
