### ISSUE TITLE
52 is the new 64?

### ISSUE THREAD

**Issue by Tiogshi** [stationeering/stationeers-ic#8]
![image](https://user-images.githubusercontent.com/198073/59557175-435cf300-8f88-11e9-8516-bd3a62a8e4b1.png)

Blaming https://github.com/stationeering/stationeers-ic/blob/863c408ec35c7e1d672fb830a1d0f01d4fb2ecc2/src/IC.js#L163

**Comment by melair** [comment]
Sorry for not seeing this for almost a year, emails from this github account go to a place I rarely check... sorry. You probably don't care anymore, but it'll be fixed when I roll out a new version of the website today.
